import { CollectionConfig } from 'payload'

export const Properties: CollectionConfig = {
  slug: 'properties',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'transactionType', 'price', 'status', 'agency'],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      label: 'Titre',
    },
    {
      name: 'slug',
      type: 'text',
      unique: true,
      admin: { position: 'sidebar' },
    },
    {
      name: 'description',
      type: 'richText',
      label: 'Description',
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Brouillon', value: 'draft' },
        { label: 'En attente', value: 'pending' },
        { label: 'Publié', value: 'published' },
        { label: 'Sous compromis', value: 'underOffer' },
        { label: 'Vendu/Loué', value: 'sold' },
      ],
      admin: { position: 'sidebar' },
    },
    {
      name: 'transactionType',
      type: 'select',
      required: true,
      options: [
        { label: 'Vente', value: 'sale' },
        { label: 'Location', value: 'rent' },
        { label: 'Location saisonnière', value: 'seasonal' },
        { label: 'Programme neuf', value: 'new' },
      ],
      label: 'Type de transaction',
    },
    {
      name: 'propertyType',
      type: 'select',
      required: true,
      options: [
        { label: 'Appartement', value: 'apartment' },
        { label: 'Maison', value: 'house' },
        { label: 'Villa', value: 'villa' },
        { label: 'Studio', value: 'studio' },
        { label: 'Terrain', value: 'land' },
        { label: 'Bureau', value: 'office' },
        { label: 'Local commercial', value: 'commercial' },
        { label: 'Entrepôt', value: 'warehouse' },
        { label: 'Fonds de commerce', value: 'business' },
        { label: 'Parking', value: 'parking' },
      ],
      label: 'Type de bien',
    },
    {
      name: 'price',
      type: 'number',
      required: true,
      min: 0,
      label: 'Prix (€)',
    },
    {
      name: 'charges',
      type: 'number',
      min: 0,
      label: 'Charges (€/mois)',
    },
    {
      name: 'surface',
      type: 'number',
      min: 0,
      label: 'Surface (m²)',
    },
    {
      name: 'landSurface',
      type: 'number',
      min: 0,
      label: 'Surface terrain (m²)',
    },
    {
      name: 'rooms',
      type: 'number',
      min: 0,
      label: 'Pièces',
    },
    {
      name: 'bedrooms',
      type: 'number',
      min: 0,
      label: 'Chambres',
    },
    {
      name: 'bathrooms',
      type: 'number',
      min: 0,
      label: 'Salles de bain',
    },
    {
      name: 'yearBuilt',
      type: 'number',
      label: 'Année construction',
    },
    {
      name: 'features',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Piscine', value: 'pool' },
        { label: 'Terrasse', value: 'terrace' },
        { label: 'Balcon', value: 'balcony' },
        { label: 'Jardin', value: 'garden' },
        { label: 'Vue mer', value: 'seaView' },
        { label: 'Cave', value: 'cellar' },
        { label: 'Ascenseur', value: 'elevator' },
        { label: 'Parking', value: 'parking' },
        { label: 'Meublé', value: 'furnished' },
        { label: 'Climatisation', value: 'aircon' },
      ],
      label: 'Équipements',
    },
    {
      name: 'energyClass',
      type: 'select',
      options: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'NS'].map((v) => ({ label: v, value: v })),
      label: 'Classe énergie',
    },
    {
      name: 'gesClass',
      type: 'select',
      options: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'NS'].map((v) => ({ label: v, value: v })),
      label: 'Classe GES',
    },
    {
      name: 'address',
      type: 'text',
      label: 'Adresse',
    },
    {
      name: 'postalCode',
      type: 'text',
      label: 'Code postal',
    },
    {
      name: 'city',
      type: 'relationship',
      relationTo: 'cities',
      label: 'Ville',
    },
    {
      name: 'island',
      type: 'relationship',
      relationTo: 'islands',
      required: true,
      label: 'Île',
    },
    {
      name: 'latitude',
      type: 'number',
      label: 'Latitude',
    },
    {
      name: 'longitude',
      type: 'number',
      label: 'Longitude',
    },
    {
      name: 'featuredImage',
      type: 'upload',
      relationTo: 'media',
      label: 'Image principale',
    },
    {
      name: 'images',
      type: 'array',
      label: 'Galerie photos',
      fields: [
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: true,
        },
      ],
    },
    {
      name: 'agency',
      type: 'relationship',
      relationTo: 'agencies',
      required: true,
      label: 'Agence',
      admin: { position: 'sidebar' },
    },
    {
      name: 'agent',
      type: 'relationship',
      relationTo: 'users',
      label: 'Agent',
      admin: { position: 'sidebar' },
    },
    {
      name: 'ubiflowId',
      type: 'text',
      label: 'ID Ubiflow',
      admin: { position: 'sidebar', readOnly: true },
    },
    {
      name: 'ubiflowRef',
      type: 'text',
      label: 'Référence Ubiflow',
      admin: { position: 'sidebar', readOnly: true },
    },
    {
      name: 'views',
      type: 'number',
      defaultValue: 0,
      admin: { position: 'sidebar', readOnly: true },
    },
  ],
}
